[package]
name = "scma-gcal-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.0.4", features = ["derive"] }
reqwest = { version = "0.11", features = ["cookies"] }
futures = "0.3"
tokio = { version = "1", features = ["full"] }
tracing = "0.1"
tracing-subscriber = "0.2"
select = "0.5.0"
serde = { version = "1.0.133", features = ["derive"] }

[dev-dependencies]
insta = "1.10.0"
