[package]
name = "scma-gcal-sync"
version = "2.0.1"
edition = "2021"
authors = ["Rob Donnelly <rfdonnelly@gmail.com>"]
description = "Synchronizes Southern California Mountaineers Association (SCMA) calendar events to Google Calendar"
license = "MIT OR Apache-2.0"
repository = "https://github.com/rfdonnelly/scma-gcal-sync"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.0.5", features = ["derive", "env"] }
reqwest = { version = "0.11.8", features = ["cookies"] }
futures = "0.3.19"
tokio = { version = "1.15.0", features = ["full"] }
tracing = "0.1.29"
tracing-subscriber = { version = "0.3.5", features = ["env-filter"] }
select = "0.5.0"
serde = { version = "1.0.133", features = ["derive"] }
serde_yaml = "0.8.23"
chrono = { version = "0.4.19", features = ["serde"] }
tap = "1.0.1"
yup-oauth2 = "5"
google-calendar3 = "2.0.8"
hyper = "^0.14"
hyper-rustls = "^0.22"
serde_json = "1.0.74"
html-escape = "0.2.9"
google-people1 = "2.0.8"
indexmap = "1"
anyhow = "1.0.56"

[dev-dependencies]
insta = "1.10.0"
