[package]
name = "scma-gcal-sync"
version = "2.0.4"
edition = "2021"
authors = ["Rob Donnelly <rfdonnelly@gmail.com>"]
description = "Synchronizes Southern California Mountaineers Association (SCMA) calendar events to Google Calendar"
license = "MIT OR Apache-2.0"
repository = "https://github.com/rfdonnelly/scma-gcal-sync"

[profile.release]
strip = true
# Optimize for size
opt-level = "z"
lto = true

[dependencies]
clap = { version = "4", features = ["derive", "env"] }
reqwest = { version = "0.11", default-features = false, features = ["cookies", "rustls-tls"] }
futures = "0.3"
tokio = { version = "1", features = ["full"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
select = "0.6"
serde = { version = "1", features = ["derive"] }
serde_yaml = "0.9"
chrono = { version = "0.4", features = ["clock", "serde"], default-features = false }
tap = "1"
# Needs to match the version used by google-calendar3 and google-people1
yup-oauth2 = "7"
google-calendar3 = "4"
hyper = "0.14"
hyper-rustls = "0.23"
serde_json = "1"
html-escape = "0.2"
google-people1 = "4"
indexmap = "1"
anyhow = "1"

[dev-dependencies]
insta = { version = "1", features = ["yaml"] }
