= SCMA Google Calendar Sync

[link=https://github.com/rfdonnelly/scma-gcal-sync/actions/workflows/ci.yml]
image::https://github.com/rfdonnelly/scma-gcal-sync/actions/workflows/ci.yml/badge.svg[CI]

Synchronizes link:https://rockclimbing.org[Southern California Mountaineers Association (SCMA)] calendar events to Google Calendar.

== Credentials

SCMA website username::
Specified via the `SCMA_USERNAME` environment variable or the `-u|--username` option.

SCMA website password::
Specified via the `SCMA_PASSWORD` environment variable or the `-p|--password` option.

Google Calendar::
TBD

== Logging

Logging is available via the `RUST_LOG` environment variable.
Use `RUST_LOG=info`.

[source,sh]
.Logging Example
----
RUST_LOG=info scma-gcal-sync
----

== Examples

=== Web to YAML

Fetches events from the SCMA website and converts them to YAML.

 scma-gcal-sync -u <scma-username> -p <scma-password> -o yaml > events.yml

=== YAML to GCal

 scma-gcal-sync -i yaml --ifile events.yml

=== Web to GCAL

 scma-gcal-sync -u <scma-username> -p <scma-password>

== Limitations

Only all-day events are supported.
SCMA events that are not all-day events are converted to all-day events.
Effectively, the time information is stripped.
