= SCMA Google Calendar Sync

[link=https://github.com/rfdonnelly/scma-gcal-sync/actions/workflows/ci.yml]
image::https://github.com/rfdonnelly/scma-gcal-sync/actions/workflows/ci.yml/badge.svg[CI]

Synchronizes link:https://rockclimbing.org[Southern California Mountaineers Association (SCMA)] calendar events to Google Calendar.

== Credentials

SCMA website username::
Specified via the `SCMA_USERNAME` environment variable or the `-u|--username` option.

SCMA website password::
Specified via the `SCMA_PASSWORD` environment variable or the `-p|--password` option.

Google Calendar client secret::
Obtain OAuth client ID credentials via the link:https://console.developers.google.com[Google Developer Console].
Stored as a JSON file.
Path to JSON file specified via the `GCAL_CLIENT_SECRET_PATH` environment variable or the `--client-secret-json-path` option.
Default path is `client_secret.json`.
+
.Create a project
.Add Google Calendar API
.Create OAuth Client ID credentials
.Download OAuth Client ID JSON
.Configure OAuth consent screen
.. Add `https://wwww.googleapis.com/auth/calendar` scope
.. Add email to test users

Google Calendar OAuth token::
Obtain on first run of `scma-gcal-sync` with gcal output.
Follow on screen instructions.
Stored as a JSON file.
Path to JSON file specified via the `GCAL_OAUTH_TOKEN_JSON_PATH` environment variable or the `--oauth-token-json-path` option.
Default path is `token.json`.

== Examples

=== Web to YAML

Fetches events from the SCMA website and converts them to YAML.

 scma-gcal-sync -u <scma-username> -p <scma-password> -o yaml > events.yml

=== YAML to GCal

 scma-gcal-sync -i yaml --ifile events.yml

=== Web to GCAL

 scma-gcal-sync -u <scma-username> -p <scma-password>

== Limitations

Only all-day events are supported.
SCMA events that are not all-day events are converted to all-day events.
Effectively, the time information is stripped.
