= SCMA Google Calendar Sync

image:https://github.com/rfdonnelly/scma-gcal-sync/actions/workflows/ci.yml/badge.svg[CI, link=https://github.com/rfdonnelly/scma-gcal-sync/actions/workflows/ci.yml]
image:https://github.com/rfdonnelly/scma-gcal-sync/actions/workflows/shared-calendar-sync.yml/badge.svg[Google Calendar Sync, link=https://github.com/rfdonnelly/scma-gcal-sync/actions/workflows/shared-calendar-sync.yml]

Synchronizes link:https://rockclimbing.org[Southern California Mountaineers Association (SCMA)] calendar events to Google Calendar.

link:https://calendar.google.com/calendar/u/0/r?cid=07i8hndd8k4a4ubhicqie9sak4@group.calendar.google.com[Add to Google Calendar]

[link=https://asciinema.org/a/3jH3c0B7XrRf1gimik3AkOJYY]
image::https://asciinema.org/a/3jH3c0B7XrRf1gimik3AkOJYY.svg[asciicast]

== Documentation

* link:docs/user-guide.adoc[User guide] -- How to synchronize SCMA member information to your personal Google Contacts
* link:docs/admin-guide.adoc[Administrator guide] -- How to maintain the shared SCMA Google Calendar
* link:docs/examples.adoc[Invocation examples] -- Various invocation examples

== Limitations

Only all-day events are supported.
SCMA events that are not all-day events are converted to all-day events.
Effectively, the time information is stripped.

== License

Licensed under either of

* Apache License, Version 2.0 (link:LICENSE-APACHE[LICENSE-APACHE] or http://www.apache.org/licenses/LICENSE-2.0)
* MIT license (link:LICENSE-MIT[LICENSE-MIT] or http://opensource.org/licenses/MIT)

at your option.

== Contribution

Unless you explicitly state otherwise, any contribution intentionally submitted for inclusion in the work by you, as defined in the Apache-2.0 license, shall be dual licensed as above, without any additional terms or conditions.
