= SCMA Google Calendar Sync

image:https://github.com/rfdonnelly/scma-gcal-sync/actions/workflows/ci.yml/badge.svg[CI, link=https://github.com/rfdonnelly/scma-gcal-sync/actions/workflows/ci.yml]
image:https://github.com/rfdonnelly/scma-gcal-sync/actions/workflows/sync-events.yml/badge.svg[Event Sync, link=https://github.com/rfdonnelly/scma-gcal-sync/actions/workflows/sync-events.yml]

Synchronizes link:https://rockclimbing.org[Southern California Mountaineers Association (SCMA)] calendar events to Google Calendar.

[link=https://asciinema.org/a/3jH3c0B7XrRf1gimik3AkOJYY]
image::https://asciinema.org/a/3jH3c0B7XrRf1gimik3AkOJYY.svg[asciicast]

== Credentials

SCMA website username::
Specified via the `SCMA_USERNAME` environment variable or the `-u|--username` option.

SCMA website password::
Specified via the `SCMA_PASSWORD` environment variable or the `-p|--password` option.

Google Calendar client secret::
Obtain OAuth client ID credentials via the link:https://console.developers.google.com[Google Developer Console].
Stored as a JSON file.
Path to JSON file specified via the `GCAL_CLIENT_SECRET_PATH` environment variable or the `--client-secret-json-path` option.
Default path is `client_secret.json`.
+
. Create a project
. Add Google Calendar API
. Create OAuth Client ID credentials
. Download OAuth Client ID JSON
. Configure OAuth consent screen
.. Add `https://wwww.googleapis.com/auth/calendar` scope
.. Add email to test users

Google Calendar OAuth token::
Obtain on first run of `scma-gcal-sync` with gcal output.
Follow on screen instructions.
Stored as a JSON file.
Path to JSON file specified via the `GCAL_OAUTH_TOKEN_JSON_PATH` environment variable or the `--oauth-token-json-path` option.
Default path is `token.json`.

== Examples

=== Events

The following examples operate on events.

==== Web to YAML

Fetch events from the SCMA website and converts them to YAML.

 scma-gcal-sync -u <scma-username> -p <scma-password> -o yaml > events.yml

==== YAML to GCal

Read events from a YAML file and sync them to Google Calendar.

 scma-gcal-sync -i yaml --ifile events.yml

==== Web to GCAL

Fetch events from the SCMA website and sync them to Google Calendar.

 scma-gcal-sync -u <scma-username> -p <scma-password>

=== Users

The following examples operate on users.

==== Web to YAML

Fetch users from the SCMA website and converts them to YAML.

 scma-gcal-sync -d users -u <scma-username> -p <scma-password> -o yaml > users.yml

==== YAML to GCal

Read users from a YAML file and sync them to the Access Control List (ACL) for Google Calendar.

 scma-gcal-sync -d users -i yaml --ifile users.yml

==== Web to GCal

Fetch users from the SCMA website and sync them to the Access Control List (ACL) for Google Calendar.

 scma-gcal-sync -d users -u <scma-username> -p <scma-password>

== Limitations

Only all-day events are supported.
SCMA events that are not all-day events are converted to all-day events.
Effectively, the time information is stripped.

== License

Licensed under either of

* Apache License, Version 2.0 (link:LICENSE-APACHE[LICENSE-APACHE] or http://www.apache.org/licenses/LICENSE-2.0)
* MIT license (link:LICENSE-MIT[LICENSE-MIT] or http://opensource.org/licenses/MIT)

at your option.

== Contribution

Unless you explicitly state otherwise, any contribution intentionally submitted for inclusion in the work by you, as defined in the Apache-2.0 license, shall be dual licensed as above, without any additional terms or conditions.
