= Release Process

This project uses https://opensource.axo.dev/cargo-dist/[cargo-dist] and https://github.com/crate-ci/cargo-release[cargo-release] to simplify cutting new releases.

== Update the Changelog

 vim CHANGELOG.md
 git add CHANGELOG
 git commit
 git push

== Create a Release

Reference: https://opensource.axo.dev/cargo-dist/book/workspaces/cargo-release-guide.html#using-cargo-release-with-pull-requests[Using cargo-release with Pull Requests]

. Create a release branch
+
 git checkout -b $BRANCH

. Update CHANGELOG
+
 vim CHANGELOG.md
 git add -p
 git commit

. Update version in `Cargo.toml`, add, commit, and push
+
 cargo release --no-publish --no-tag --allow-branch $BRANCH $VERSION
+
E.g.,
+
 cargo release --no-public --no-tag --allow-branch r1.0.1 1.0.1

. Open a PR, review, and merge to main

. Pull main, dist plan
+
 git checkout main
 git pull
 dist plan

. Tag, push tag, trigger dist
+
 cargo release

== Sit Back and Relax

Sit back and relax while `cargo-dist` automatically creates a GitHub Release and releases binaries for each platform.
