= Examples
:toc:

== Events

The following examples operate on events.

=== SCMA to YAML

Fetch events from the SCMA website and converts them to YAML.

 scma-gsync events -u <scma-username> -p <scma-password> -o yaml > events.yml

=== YAML to Google Calendar

Read events from a YAML file and sync them to Google Calendar.

 scma-gsync events -i yaml --ifile events.yml

=== SCMA to Google Calendar

Fetch events from the SCMA website and sync them to Google Calendar.

 scma-gsync events -u <scma-username> -p <scma-password>

== Users

The following examples operate on users.

=== SCMA to YAML

Fetch users from the SCMA website and converts them to YAML.

 scma-gsync users -u <scma-username> -p <scma-password> -o yaml > users.yml

=== YAML to Google Calendar

Read users from a YAML file and sync them to the Access Control List (ACL) for Google Calendar.

 scma-gsync users -i yaml --ifile users.yml

=== SCMA to Google Calendar

Fetch users from the SCMA website and sync them to the Access Control List (ACL) for Google Calendar.

 scma-gsync users -u <scma-username> -p <scma-password>

=== YAML to Google Contacts

Reads users from a YAML file and sync them to Google Contacts.

 scma-gsync users -i yaml --ifile users.yml -o gppl

=== SCMA to Google Contacts

Fetch users from the SCMA website and sync them to Google Contacts.

 scma-gsync users -u <scma-username> -p <scma-password> -o gppl

