name: Personal Calendar Sync
on:
  workflow_dispatch:
  schedule:
    # Run every day at 2am PST (10am UTC)
    - cron: '0 10 * * *'

jobs:
  build:
    name: Personal Calendar Sync
    runs-on: ubuntu-latest
    steps:
      - name: Download latest release
        uses: robinraju/release-downloader@v1.3
        with:
          repository: rfdonnelly/scma-gcal-sync
          latest: true
          fileName: scma-gcal-sync
      - name: Set execute permissions
        run: chmod +x scma-gcal-sync
      - name: Populate credentials
        run: |
          echo "$GOOGLE_OAUTH_CLIENT_SECRET_JSON" > secret.json
          echo "$GOOGLE_OAUTH_TOKEN_JSON" > token.json
        env:
          GOOGLE_OAUTH_CLIENT_SECRET_JSON: ${{ secrets.GOOGLE_OAUTH_CLIENT_SECRET_JSON }}
          GOOGLE_OAUTH_TOKEN_JSON: ${{ secrets.GOOGLE_OAUTH_TOKEN_JSON }}
      - name: Sync Events
        run: ./scma-gcal-sync events --auth-type oauth
        env:
          SCMA_USERNAME: ${{ secrets.SCMA_USERNAME }}
          SCMA_PASSWORD: ${{ secrets.SCMA_PASSWORD }}
