name: Shared Calendar Sync
on:
  workflow_dispatch:
  schedule:
      # Run every day at 2:30am PST (10:30am UTC)
    - cron: '30 10 * * *'

jobs:
  build:
    name: Shared Calendar Sync
    runs-on: ubuntu-latest
    steps:
      - name: Download latest release
        uses: robinraju/release-downloader@v1.5
        with:
          repository: rfdonnelly/scma-gcal-sync
          latest: true
          fileName: scma-gcal-sync
      - name: Set execute permissions
        run: chmod +x scma-gcal-sync
      - name: Populate credentials
        env:
          GOOGLE_SERVICE_ACCOUNT_JSON: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON }}
        run: |
          echo "$GOOGLE_SERVICE_ACCOUNT_JSON" > secret-service-account.json
      - name: Sync Events
        env:
          SCMA_USERNAME: ${{ secrets.SCMA_USERNAME }}
          SCMA_PASSWORD: ${{ secrets.SCMA_PASSWORD }}
        run: >
          ./scma-gcal-sync events
            --input web
            --output gcal
            --calendar SCMA
            --auth-type service-account
            --secret-file secret-service-account.json
      - name: Populate email aliases
        env:
          EMAIL_ALIASES: ${{ secrets.EMAIL_ALIASES }}
        run: |
          echo "$EMAIL_ALIASES" > email-aliases.yml
          cat email-aliases.yml
      - name: Sync ACL
        env:
          SCMA_USERNAME: ${{ secrets.SCMA_USERNAME }}
          SCMA_PASSWORD: ${{ secrets.SCMA_PASSWORD }}
        run: >
          ./scma-gcal-sync users
            --input web
            --output gcal
            --calendar SCMA
            --email-aliases-file email-aliases.yml
            --auth-type service-account
            --secret-file secret-service-account.json
            --notify-acl-insert true
