name: Sync
on:
  workflow_dispatch:
  push:
  schedule:
    # Run every day at 2am
    - cron: '0 2 * * *'

jobs:
  build:
    name: Sync
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Run cargo build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
      - name: Populate credentials
        run: |
          echo "$GCAL_CLIENT_SECRET_JSON" > client_secret.json
          echo "$GCAL_OAUTH_TOKEN_JSON" > token.json
        env:
          GCAL_CLIENT_SECRET_JSON: ${{ secrets.GCAL_CLIENT_SECRET_JSON }}
          GCAL_OAUTH_TOKEN_JSON: ${{ secrets.GCAL_OAUTH_TOKEN_JSON }}
      - name: Sync
        run: target/release/scma-gcal-sync
        env:
          SCMA_USERNAME: ${{ secrets.SCMA_USERNAME }}
          SCMA_PASSWORD: ${{ secrets.SCMA_PASSWORD }}
