name: Sync
on:
  workflow_dispatch:
  schedule:
    # Run every day at 2am
    - cron: '0 2 * * *'

jobs:
  build:
    name: Sync
    runs-on: ubuntu-latest
    steps:
      - name: Download latest release
        uses: robinraju/release-downloader@v1.3
        with:
          repository: rfdonnelly/scma-gcal-sync
          latest: true
          fileName: scma-gcal-sync
      - name: Set execute permissions
        run: chmod +x scma-gcal-sync
      - name: Populate credentials
        run: |
          echo "$GCAL_CLIENT_SECRET_JSON" > client_secret.json
          echo "$GCAL_OAUTH_TOKEN_JSON" > token.json
        env:
          GCAL_CLIENT_SECRET_JSON: ${{ secrets.GCAL_CLIENT_SECRET_JSON }}
          GCAL_OAUTH_TOKEN_JSON: ${{ secrets.GCAL_OAUTH_TOKEN_JSON }}
      - name: Sync
        run: ./scma-gcal-sync
        env:
          SCMA_USERNAME: ${{ secrets.SCMA_USERNAME }}
          SCMA_PASSWORD: ${{ secrets.SCMA_PASSWORD }}
